### ISSUE TITLE
Not works in android

### ISSUE THREAD

**Issue by Ivanzar** [Kronos666/rkon-core#4]
Hi, I get this error while I am using this library in android but in PC it is work
`net.kronos.rkon.core.ex.MalformedPacketException: Cannot read the whole packet
	 at net.kronos.rkon.core.RconPacket.read(RconPacket.java:136)
     at net.kronos.rkon.core.RconPacket.send(RconPacket.java:65)
     at net.kronos.rkon.core.Rcon.send(Rcon.java:106)
     at net.kronos.rkon.core.Rcon.command(Rcon.java:99)
     at ivanzar.servertools.rcon.RconTask.doInBackground(RconTask.java:66)
     at ivanzar.servertools.rcon.RconTask.doInBackground(RconTask.java:25)
     at android.os.AsyncTask$2.call(AsyncTask.java:288)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)`

```java
Rcon rcon;

        try {
            rcon = new Rcon(ip, port, pass.getBytes());
        } catch (IOException e) {
            e.printStackTrace();
            err = ERR_UNKNOWN_HOST;
            return;
        } catch (AuthenticationException e) {
            e.printStackTrace();
            err = ERR_UNKNOWN_HOST;
            return;
        }

        try {
            out = rcon.command(cmd);
            err = NO_ERRORS;
        } catch (IOException e) {
            e.printStackTrace();
            err = ERR_IO_EXCEPTION;
            return;
        }
```

**Comment by Ivanzar** [comment]
I am fixing this when I rewrite this code:
```java
ByteBuffer buffer = ByteBuffer.wrap(receiveBuffer, 0, bytesRead);
```
on:
```java
ByteBuffer buffer = ByteBuffer.wrap(receiveBuffer, 0, READ_BUFFER_SIZE);
```
